// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_ruins_because_of_earthquake_story = "CgkIoKb1_N4aEAIQDw"; // <GPGSID>
        public const string leaderboard_sangsit_village_story = "CgkIoKb1_N4aEAIQCA"; // <GPGSID>
        public const string leaderboard_barong_dance_challenge = "CgkIoKb1_N4aEAIQFA"; // <GPGSID>
        public const string leaderboard_traditional_market_challenge = "CgkIoKb1_N4aEAIQEg"; // <GPGSID>
        public const string leaderboard_kingdom_of_balingkang_story = "CgkIoKb1_N4aEAIQEQ"; // <GPGSID>
        public const string leaderboard_forest_story = "CgkIoKb1_N4aEAIQCQ"; // <GPGSID>
        public const string achievement_a = "CgkIoKb1_N4aEAIQAQ"; // <GPGSID>
        public const string achievement_b = "CgkIoKb1_N4aEAIQAg"; // <GPGSID>
        public const string achievement_c = "CgkIoKb1_N4aEAIQBA"; // <GPGSID>
        public const string achievement_d = "CgkIoKb1_N4aEAIQBQ"; // <GPGSID>
        public const string achievement_e = "CgkIoKb1_N4aEAIQBg"; // <GPGSID>
        public const string leaderboard_barong_dance_story = "CgkIoKb1_N4aEAIQEA"; // <GPGSID>
        public const string leaderboard_kingdom_of_balingkang_challenge = "CgkIoKb1_N4aEAIQFQ"; // <GPGSID>
        public const string leaderboard_traditional_market_story = "CgkIoKb1_N4aEAIQDg"; // <GPGSID>
        public const string leaderboard_forest_challenge = "CgkIoKb1_N4aEAIQDA"; // <GPGSID>
        public const string leaderboard_ruins_because_of_earthquake_challenge = "CgkIoKb1_N4aEAIQEw"; // <GPGSID>
        public const string leaderboard_dragons_lair_story = "CgkIoKb1_N4aEAIQCg"; // <GPGSID>
        public const string leaderboard_sangsit_village_challenge = "CgkIoKb1_N4aEAIQCw"; // <GPGSID>
        public const string leaderboard_dragons_lair_challenge = "CgkIoKb1_N4aEAIQDQ"; // <GPGSID>

}

